POST http://localhost:3000/api/getdata HTTP/1.1
content-type: application/json

{
    "col": "AMP_CODE",
    "val": "5206"
}

###
POST http://localhost:3000/api/get_by_region HTTP/1:1
Content-Type: application/json

{
    "address_code":"01"            
}

// address_code = "01" "02"

###
POST http://localhost:3000/api/get_by_province HTTP/1:1
Content-Type: application/json

{
    "province_code":"40"           
}

// "province_code" = "ALL", "02", "04", ... (รหัสจังหวัด)

###
POST http://localhost:3000/api/get_by_amp HTTP/1:1
Content-Type: application/json

{
    "province_code":"40",
    "amphoe_code": "4005"          
}


###
POST http://localhost:3000/api/get_by_tam HTTP/1:1
Content-Type: application/json

{
    "amphoe_code":"4005",
    "tambon_code": ""          
}

