SELECT  * FROM  MN_DES_DEFORMED_ASSESS mdas;
SELECT count(MAIMAD_ID) FROM  MN_DES_PERSON mdp 
SELECT  count(MAIMAD_ID) FROM MN_DES_ADDRESS mda

SELECT count(MAIMAD_ID) FROM MN_DES_DEFORMED
SELECT * FROM MN_DES_DEFORMED
SELECT count(MAIMAD_ID) FROM MN_DES_ADDRESS mda WHERE ADDRESS_CODE = '02'

SELECT MAIMAD_ID,
count(MAIMAD_ID)
FROM MN_DES_DEFORMED
GROUP BY MAIMAD_ID;



SELECT count(mdp.MAIMAD_ID) 
SELECT mda.*,mdp.*
FROM MN_DES_PERSON mdp 
inner JOIN (SELECT * FROM MN_DES_ADDRESS WHERE ADDRESS_CODE = '02') mda ON mdp.MAIMAD_ID = mda.MAIMAD_ID
inner JOIN (SELECT * FROM MN_DES_ADDRESS WHERE ADDRESS_CODE = '02') mda ON mdp.MAIMAD_ID = mdd.MAIMAD_ID 
ORDER BY mdp.MAIMAD_ID asc
--LEFT JOIN MN_DES_DEFORMED mdd ON mdp.MAIMAD_ID = mdd.MAIMAD_ID 
WHERE mda.MAIMAD_ID IS NULL
WHERE ROWNUM <= 100


SELECT * FROM V_MN_DES_PERSON

INSERT INTO  test(col1, col2, dt)values(11, 'sakda', '2022-0 8-07')


SELECT  
	count(SEX_CODE) AS total,
	sum(CASE SEX_CODE WHEN 'F' THEN 1 ELSE 0 END) AS f,
	sum(CASE SEX_CODE WHEN 'M' THEN 1 ELSE 0 END) AS m
FROM V_MN_DES_PERSON


SELECT count(SEX_CODE) FROM V_MN_DES_PERSON WHERE SEX_CODE = 'F';
SELECT count(SEX_CODE) FROM V_MN_DES_PERSON WHERE SEX_CODE = 'M';

