SELECT * FROM MN_DES_ADDRESS
SELECT * FROM "OPP$_DBA".MN_DES_ADDRESS_HIS
SELECT * FROM "OPP$_DBA".MN_DES_CURATOR
SELECT * FROM "OPP$_DBA".MN_DES_CURATOR_ADDRESS

SELECT * FROM "OPP$_DBA".MN_DES_CURATOR_MAIMAD
SELECT * FROM "OPP$_DBA".MN_DES_DEFORMED
SELECT * FROM "OPP$_DBA".MN_DES_DEFORMED_ASSESS

SELECT * FROM "OPP$_DBA".MN_DES_DEFORMED_SUBTYPE
SELECT * FROM "OPP$_DBA".MN_DES_DEFORMED_SUBTYPE_DETAIL
SELECT * FROM "OPP$_DBA".MN_DES_PERSON
SELECT * FROM "OPP$_DBA".MN_HIS_CURATOR

SELECT * FROM "OPP$_DBA".MN_HIS_CURATOR_ADDRESS
SELECT * FROM "OPP$_DBA".MN_HIS_CURATOR_MAIMAD